### ISSUE TITLE
Fix parse_token function

### ISSUE THREAD

**Issue by federicojasson** [nhuff/chef-augeas#11]
Source: https://github.com/nhuff/chef-augeas/blob/master/libraries/augeas_provider.rb#L247
If the input contains an odd number of any of `'`, `"`, `(`, `)`, `[`, `]`, the function raises an error. This may be intended for commands, but if one wants to set an arbitrary value in a file, like `foo [ bar`, it's not possible.

Source: https://github.com/nhuff/chef-augeas/blob/master/libraries/augeas_provider.rb#L306
Also, the `path` variable is undefined, so a generic `undefined local variable or method 'path' for #<Chef::Provider::Augeas:0x00000006053a88>` error is raised when the above condition occurs.

**Comment by nhuff** [comment]
This should hopefully be fixed by version 0.5.4 which is here now and will be pushed to the supermarket shortly.
