### ISSUE TITLE
Cannot use variable on a changes line

### ISSUE THREAD

**Issue by n3bojs4** [nhuff/chef-augeas#9]
Hi,

It seems using variable in a changes line is not possible, for example : 

AdminIp = "192.168.0.1"

augeas 'sshd' do
 changes "set /files/etc/ssh/sshd_config/ListenAddress #{AdminIp}"
 lens 'Sshd.lns'
end

#{AdminIp} is not interpreted, is this a code limitation ?

thanks for reply.

**Comment by nhuff** [comment]
It certainly should work.  I would think the string would get expanded during the parsing of the recipe and so the provider shouldn't even see the unexpanded string.  I will see if I can recreate.

**Comment by n3bojs4** [comment]
Sorry it seems it works correctly !
I tried to update the code with a new method, and through debugging process i found that your code wasn't the symptom.
